name: CI

on:
  push:
    branches:
      - master
      - release/**

  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --component clippy rustfmt --no-self-update

      - name: Run Rustfmt
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features --no-deps -- -D warnings

      - name: Check Docs
        run: cargo doc --workspace --all-features --no-deps
        env:
          RUSTDOCFLAGS: -Dwarnings

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Run Cargo Tests
        run: cargo test --workspace --all-features
        env:
          TZ: CEST
